/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogParsingRouteImport } from './routes/log-parsing'
import { Route as LogMetricsRouteImport } from './routes/log-metrics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const LogParsingRoute = LogParsingRouteImport.update({
  id: '/log-parsing',
  path: '/log-parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogMetricsRoute = LogMetricsRouteImport.update({
  id: '/log-metrics',
  path: '/log-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/log-metrics': typeof LogMetricsRoute
  '/log-parsing': typeof LogParsingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/log-metrics': typeof LogMetricsRoute
  '/log-parsing': typeof LogParsingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/log-metrics': typeof LogMetricsRoute
  '/log-parsing': typeof LogParsingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/log-metrics' | '/log-parsing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/log-metrics' | '/log-parsing'
  id: '__root__' | '/' | '/alerts' | '/log-metrics' | '/log-parsing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  LogMetricsRoute: typeof LogMetricsRoute
  LogParsingRoute: typeof LogParsingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/log-parsing': {
      id: '/log-parsing'
      path: '/log-parsing'
      fullPath: '/log-parsing'
      preLoaderRoute: typeof LogParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-metrics': {
      id: '/log-metrics'
      path: '/log-metrics'
      fullPath: '/log-metrics'
      preLoaderRoute: typeof LogMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  LogMetricsRoute: LogMetricsRoute,
  LogParsingRoute: LogParsingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
